### ISSUE TITLE
Configuring your Git installation

### ISSUE THREAD

**Issue by BroVic** [NESREA/WMGtraining#4]
When you are carrying out commits, Git needs to know who you are. The same is applied to when you want to work with the remote repository. To configure Git do the following:
```
git config --global user.name 'Your name'
git config --global user.email myemail@somewhere.com
```
That's all.

Remember to use your real name, separate the first and last name, and put the names together in quotes e.g. "John Musa". For the email, just type it out the way it is.

Now, if you haven't forked this repo already, do so now and clone it to your computer. You should  do so inside the folder you created during the training session. As a reminder, to clone you will run the following command in Git (internet connection required);
```
git clone https://github.com/<your username>/WMGTraining.git
```
If it were me, my command would look like this:
```
git clone https://github.com/BroVic/WMGTraining.git
```
You can comment below to let me know how it goes.

Cheers. :nigeria:

**Comment by obroma** [comment]
your directive was very useful, i was able to fork a document but was having problem using  RStudio to run the script

**Comment by BroVic** [comment]
Cool. 
As for the document you mentioned, you can do 2 things:
1. Share with us here - what the problem was, what error messages you are getting, etc.
2. Post an issue on the original repository and see what the owner has to say about it.
3. Do both - by posting a detailed issue for the owner's attention and "reference" it here using the ribbon on the upper right hand corner of the comment box.



@obroma
